version: "3.9"

services:
  db:
    image: postgres:17.6
    container_name: kb_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kb_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  adminer:
    image: adminer:latest
    container_name: kb_adminer
    ports:
      - "8080:8080"
    depends_on:
      - db

  server:
    build: ./server
    container_name: kb_server
    env_file:
      - .env
    environment:
      SERVER_PORT: 5000
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - server_node_modules:/app/node_modules
      - ./db:/db
    depends_on:
      - db

  client:
    build: ./client
    container_name: kb_client
    environment:
      SERVER_HOST: server
      SERVER_PORT: 5000
      PORT: 3000
      HOST: 0.0.0.0
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - client_node_modules:/app/node_modules
    depends_on:
      - server

volumes:
  db_data:
  client_node_modules:
  server_node_modules: